apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provisioning
  namespace: monitoring
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'kubernetes-dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        options:
          path: /var/lib/grafana/dashboards
