apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app: cadvisor
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      automountServiceAccountToken: false
      hostNetwork: true
      hostPID: true
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.52.1
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: var-run
              mountPath: /var/run
              readOnly: true
            - name: docker
              mountPath: /var/lib/docker
              readOnly: true
      volumes:
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: var-run
          hostPath:
            path: /var/run
            type: Directory
        - name: docker
          hostPath:
            path: /var/lib/docker
            type: Directory
