apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: kubernetes-nodes
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        # point at the API-server, not the kubelet pod directly
        relabel_configs:
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          # rewrite the path per-node so it proxies /metrics through the API-server
          - source_labels: [__meta_kubernetes_node_name]
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics
              
      - job_name: kubernetes-cadvisor
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
            
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        metrics_path: /metrics
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            regex: (.+):(?:\d+);(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
              
      - job_name: node-exporter
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: [monitoring]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: node-exporter
            action: keep
        metrics_path: /metrics
        scheme: http
    
      - job_name: kube-state-metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: [monitoring]
        relabel_configs:
          # keep only the service named kube-state-metrics
          - source_labels: [__meta_kubernetes_service_name]
            regex: kube-state-metrics
            action: keep
        metrics_path: /metrics
        scheme: http
        
      - job_name: cadvisor
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: [monitoring]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: cadvisor
            action: keep
        metrics_path: /metrics
        scheme: http
          
      - job_name: coredns
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: [kube-system]
        relabel_configs:
          # Keep only the kube-dns Service
          - source_labels: [__meta_kubernetes_service_name]
            regex: kube-dns
            action: keep
            
            # Keep only the "metrics" port (not the UDP 53 DNS port)
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: metrics
            action: keep

        metrics_path: /metrics
        scheme: http

